INSERT INTO CURRENCY_EXCHANGE
(CURR_ID, CURR_MULTI, CURR_ENV, CURR_FROM, CURR_TO )
VALUES
(10001, 2, 'env', 'USD', 'PLN');

INSERT INTO CURRENCY_EXCHANGE
(CURR_ID, CURR_MULTI, CURR_ENV, CURR_FROM, CURR_TO )
VALUES
(10002, 12, 'env', 'PLN', 'EUR');

INSERT INTO CURRENCY_EXCHANGE
(CURR_ID, CURR_MULTI, CURR_ENV, CURR_FROM, CURR_TO )
VALUES
(10003, 5, 'env', 'EUR', 'USD');
